spring.application.name=online-dictionary
server.port=8081

spring.datasource.url=jdbc:h2:file:./data/dictionary-db
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

spring.jpa.hibernate.ddl-auto=update
spring.jpa.open-in-view=false
spring.jpa.defer-datasource-initialization=true

spring.sql.init.mode=always
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

spring.thymeleaf.cache=false
